# -*- coding: utf-8 -*-
"""exp-1cv.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oxkGFHsRpDuGmGklkFqygXYAtxtsKDJU
"""

# Import necessary libraries
import cv2
import numpy as np
import matplotlib.pyplot as plt
from google.colab.patches import cv2_imshow

# Assuming the uploaded image is named 'image.jpg'
image_path = '/content/VK18.jpg'

# Read the image in RGB format
image_rgb = cv2.imread(image_path)
image_rgb = cv2.cvtColor(image_rgb, cv2.COLOR_BGR2RGB)

# Convert the image to different color spaces
image_hsv = cv2.cvtColor(image_rgb, cv2.COLOR_RGB2HSV)
image_gray = cv2.cvtColor(image_rgb, cv2.COLOR_RGB2GRAY)
image_lab = cv2.cvtColor(image_rgb, cv2.COLOR_RGB2LAB)

# Display the images using Matplotlib
plt.figure(figsize=(10, 8))

plt.subplot(2, 2, 1)
plt.title('Virat Kohli Image [Ayush Yadav || 21BCS1087]')
plt.imshow(image_rgb)
plt.axis('off')

plt.subplot(2, 2, 2)
plt.title('HSV Image')
plt.imshow(image_hsv)
plt.axis('off')

plt.subplot(2, 2, 3)
plt.title('Greyscale Image')
plt.imshow(image_gray, cmap='gray')
plt.axis('off')

plt.subplot(2, 2, 4)
plt.title('LAB Image')
plt.imshow(image_lab)
plt.axis('off')

plt.tight_layout()
plt.show()

